//! CCSDS pseudo-randomizer / derandomizer.
//!
//! Public-domain algorithm from CCSDS 131.0-B ("TM Synchronization and
//! Channel Coding"): an 8-bit LFSR with polynomial `x^8+x^7+x^5+x^3+1`,
//! seeded to `0xFF`, producing a 255-byte pseudo-random sequence that
//! repeats with period 255. Transport frame bytes (everything after the
//! CADU sync marker) are XORed with this sequence (wrapping/repeating as
//! needed) to whiten the data for the transmitter's clock recovery; XORing
//! again undoes it (it's an involution).

/// Length of one period of the CCSDS PN sequence.
pub const PN_PERIOD: usize = 255;

/// The 255-byte CCSDS pseudo-random sequence, generated once at first use.
///
/// Generated by the standard CCSDS LFSR: 8 bits of state, seeded to
/// `0xFF`, tap polynomial `x^8+x^7+x^5+x^3+1` in right-shifting Fibonacci
/// form (output = LSB shifted out, feedback `b7^b5^b3^b0` into the MSB),
/// output bytes assembled MSB-first. This exact convention is pinned by the
/// `pn_table_matches_ccsds_golden_vector` test — a left-shifting variant
/// with mirrored taps generates the time-reversed (and non-maximal) stream
/// and fails it.
fn generate_pn_table() -> [u8; PN_PERIOD] {
    let mut table = [0u8; PN_PERIOD];
    let mut state: u8 = 0xFF;
    for byte in &mut table {
        let mut out = 0u8;
        for bit_idx in 0..8 {
            // Output bit is the LSB being shifted out.
            let out_bit = state & 1;
            out |= out_bit << (7 - bit_idx);
            // Feedback taps at bits 7, 5, 3, 0 (mask 0xA9).
            let fb = ((state >> 7) ^ (state >> 5) ^ (state >> 3) ^ state) & 1;
            state = (state >> 1) | (fb << 7);
        }
        *byte = out;
    }
    table
}

/// Lazily-built, cached PN table (avoids recomputing the LFSR on every call).
fn pn_table() -> &'static [u8; PN_PERIOD] {
    use std::sync::OnceLock;
    static TABLE: OnceLock<[u8; PN_PERIOD]> = OnceLock::new();
    TABLE.get_or_init(generate_pn_table)
}

/// XOR `data` against the CCSDS PN sequence in place, wrapping every 255
/// bytes. Since XOR-with-PN is its own inverse, this both randomizes and
/// derandomizes.
pub fn derandomize_in_place(data: &mut [u8]) {
    let table = pn_table();
    for (i, byte) in data.iter_mut().enumerate() {
        *byte ^= table[i % PN_PERIOD];
    }
}

/// Non-mutating variant: returns a new derandomized `Vec`.
#[must_use]
pub fn derandomize(data: &[u8]) -> Vec<u8> {
    let mut out = data.to_vec();
    derandomize_in_place(&mut out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pn_table_has_correct_length_and_is_deterministic() {
        let t1 = pn_table();
        let t2 = pn_table();
        assert_eq!(t1.len(), PN_PERIOD);
        assert_eq!(t1, t2);
    }

    #[test]
    fn pn_table_matches_ccsds_golden_vector() {
        // Independent golden vector for the CCSDS 131.0-B TM randomizer
        // (polynomial x^8+x^7+x^5+x^3+1, seed 0xFF, MSB-first): first 32
        // bytes cross-checked between two unrelated public sources (an
        // OCaml LFSR test suite citing 131.0-B-4 §9, and Lucas Teske's
        // satellite-communications reference table). Any tap, direction,
        // seed, or bit-order error fails this with probability ~1-2^-256.
        const GOLDEN: [u8; 32] = [
            0xFF, 0x48, 0x0E, 0xC0, 0x9A, 0x0D, 0x70, 0xBC, 0x8E, 0x2C, 0x93, 0xAD, 0xA7, 0xB7,
            0x46, 0xCE, 0x5A, 0x97, 0x7D, 0xCC, 0x32, 0xA2, 0xBF, 0x3E, 0x0A, 0x10, 0xF1, 0x88,
            0x94, 0xCD, 0xEA, 0xB1,
        ];
        assert_eq!(&pn_table()[..32], &GOLDEN);
    }

    #[test]
    fn pn_bitstream_has_maximal_period_255() {
        // An 8-bit maximal LFSR repeats every 255 bits (all shorter periods
        // must divide 255: 1/3/5/15/17/51/85). Expand MSB-first and check.
        let bits: Vec<u8> = pn_table()
            .iter()
            .flat_map(|b| (0..8).map(move |i| (b >> (7 - i)) & 1))
            .collect();
        assert_eq!(bits.len(), 255 * 8);
        for i in 0..bits.len() - 255 {
            assert_eq!(bits[i], bits[i + 255], "bit {i} breaks 255-periodicity");
        }
        for short in [1usize, 3, 5, 15, 17, 51, 85] {
            assert!(
                (0..bits.len() - short).any(|i| bits[i] != bits[i + short]),
                "degenerate: period {short} also holds"
            );
        }
    }

    #[test]
    fn derandomize_is_involution() {
        let original: Vec<u8> = (0..600).map(|i| (i * 37 + 11) as u8).collect();
        let randomized = derandomize(&original);
        let restored = derandomize(&randomized);
        assert_eq!(original, restored);
    }

    #[test]
    fn derandomize_wraps_at_255_bytes() {
        let data = vec![0xAAu8; 600];
        let out = derandomize(&data);
        let table = pn_table();
        for (i, &b) in out.iter().enumerate() {
            assert_eq!(b, 0xAA ^ table[i % PN_PERIOD]);
        }
    }

    #[test]
    fn derandomize_in_place_matches_non_mutating() {
        let data = vec![1u8, 2, 3, 4, 5, 250, 251, 252];
        let mut buf = data.clone();
        derandomize_in_place(&mut buf);
        assert_eq!(buf, derandomize(&data));
    }
}
