//! CCSDS pseudo-randomizer / derandomizer.
//!
//! Public-domain algorithm from CCSDS 131.0-B ("TM Synchronization and
//! Channel Coding"): an 8-bit LFSR with polynomial `x^8+x^7+x^5+x^3+1`,
//! seeded to `0xFF`, producing a 255-byte pseudo-random sequence that
//! repeats with period 255. Transport frame bytes (everything after the
//! CADU sync marker) are XORed with this sequence (wrapping/repeating as
//! needed) to whiten the data for the transmitter's clock recovery; XORing
//! again undoes it (it's an involution).

/// Length of one period of the CCSDS PN sequence.
pub const PN_PERIOD: usize = 255;

/// The 255-byte CCSDS pseudo-random sequence, generated once at first use.
///
/// Generated by the standard CCSDS LFSR: 8 bits of state, seeded to
/// `0xFF`, tap polynomial `x^8+x^7+x^5+x^3+1`, output bit taken MSB-first
/// per output byte (bit 7 down to bit 0), matching the conventional
/// description of the CCSDS randomizer used across many independent
/// downlink standards (TM synchronization).
fn generate_pn_table() -> [u8; PN_PERIOD] {
    let mut table = [0u8; PN_PERIOD];
    // 8-bit shift register, MSB-first convention: bit7..bit0.
    let mut state: u8 = 0xFF;
    for byte in &mut table {
        let mut out = 0u8;
        for bit_idx in 0..8 {
            // Output bit is the current MSB of the register.
            let out_bit = (state >> 7) & 1;
            out |= out_bit << (7 - bit_idx);
            // Feedback polynomial x^8+x^7+x^5+x^3+1 -> taps at bits 7,5,3,0
            // (bit0 corresponds to the implicit "+1" / constant tap i.e.
            // the bit being shifted out combines with taps 7,5,3).
            let fb = ((state >> 7) ^ (state >> 5) ^ (state >> 3) ^ state) & 1;
            state = (state << 1) | fb;
        }
        *byte = out;
    }
    table
}

/// Lazily-built, cached PN table (avoids recomputing the LFSR on every call).
fn pn_table() -> &'static [u8; PN_PERIOD] {
    use std::sync::OnceLock;
    static TABLE: OnceLock<[u8; PN_PERIOD]> = OnceLock::new();
    TABLE.get_or_init(generate_pn_table)
}

/// XOR `data` against the CCSDS PN sequence in place, wrapping every 255
/// bytes. Since XOR-with-PN is its own inverse, this both randomizes and
/// derandomizes.
pub fn derandomize_in_place(data: &mut [u8]) {
    let table = pn_table();
    for (i, byte) in data.iter_mut().enumerate() {
        *byte ^= table[i % PN_PERIOD];
    }
}

/// Non-mutating variant: returns a new derandomized `Vec`.
#[must_use]
pub fn derandomize(data: &[u8]) -> Vec<u8> {
    let mut out = data.to_vec();
    derandomize_in_place(&mut out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pn_table_has_correct_length_and_is_deterministic() {
        let t1 = pn_table();
        let t2 = pn_table();
        assert_eq!(t1.len(), PN_PERIOD);
        assert_eq!(t1, t2);
    }

    #[test]
    fn pn_table_starts_with_known_seed_derived_byte() {
        // First output byte with state=0xFF should be all-ones only if the
        // feedback keeps producing 1s; just check it's deterministic and
        // not degenerate (not all-zero, not all-0xFF for the whole table).
        let t = pn_table();
        assert!(t.iter().any(|&b| b != 0));
        assert!(t.iter().any(|&b| b != 0xFF));
    }

    #[test]
    fn derandomize_is_involution() {
        let original: Vec<u8> = (0..600).map(|i| (i * 37 + 11) as u8).collect();
        let randomized = derandomize(&original);
        let restored = derandomize(&randomized);
        assert_eq!(original, restored);
    }

    #[test]
    fn derandomize_wraps_at_255_bytes() {
        let data = vec![0xAAu8; 600];
        let out = derandomize(&data);
        let table = pn_table();
        for (i, &b) in out.iter().enumerate() {
            assert_eq!(b, 0xAA ^ table[i % PN_PERIOD]);
        }
    }

    #[test]
    fn derandomize_in_place_matches_non_mutating() {
        let data = vec![1u8, 2, 3, 4, 5, 250, 251, 252];
        let mut buf = data.clone();
        derandomize_in_place(&mut buf);
        assert_eq!(buf, derandomize(&data));
    }
}
