//! CCSDS/Meteor Reed–Solomon RS(255,223) decoding with depth-four interleave.
//!
//! Meteor LRPT uses the CCSDS conventional-basis field generated by
//! `x^8 + x^7 + x^2 + x + 1` (`0x187`). The generator has 32 roots starting
//! at `alpha^112` with primitive element `alpha^11`.

pub const INTERLEAVE: usize = 4;
pub const RS_DATA_LEN: usize = 223;
pub const RS_PARITY_LEN: usize = 32;
pub const RS_CODEWORD_LEN: usize = RS_DATA_LEN + RS_PARITY_LEN;
pub const INTERLEAVED_FRAME_LEN: usize = RS_CODEWORD_LEN * INTERLEAVE;

const FIELD_SIZE: usize = 255;
const FIELD_POLY: u16 = 0x187;
const FIRST_ROOT: i32 = 112;
const PRIMITIVE_STEP: i32 = 11;

#[derive(Clone, Copy)]
struct Gf256 {
    exp: [u8; FIELD_SIZE * 2],
    log: [u8; 256],
}

const fn gf() -> Gf256 {
    let mut exp = [0u8; FIELD_SIZE * 2];
    let mut log = [u8::MAX; 256];
    let mut x = 1u16;
    let mut i = 0;
    while i < FIELD_SIZE {
        exp[i] = x as u8;
        log[x as usize] = i as u8;
        x <<= 1;
        if x & 0x100 != 0 {
            x ^= FIELD_POLY;
        }
        i += 1;
    }
    let mut j = FIELD_SIZE;
    while j < FIELD_SIZE * 2 {
        exp[j] = exp[j - FIELD_SIZE];
        j += 1;
    }
    Gf256 { exp, log }
}

const GF: Gf256 = gf();

impl Gf256 {
    #[inline]
    fn mul(self, a: u8, b: u8) -> u8 {
        if a == 0 || b == 0 {
            0
        } else {
            self.exp[usize::from(self.log[usize::from(a)]) + usize::from(self.log[usize::from(b)])]
        }
    }

    #[inline]
    fn inv(self, a: u8) -> u8 {
        assert_ne!(a, 0);
        self.exp[FIELD_SIZE - usize::from(self.log[usize::from(a)])]
    }

    #[inline]
    fn alpha(self, exponent: i32) -> u8 {
        self.exp[exponent.rem_euclid(FIELD_SIZE as i32) as usize]
    }

    #[inline]
    fn pow(self, value: u8, exponent: i32) -> u8 {
        if value == 0 {
            return u8::from(exponent == 0);
        }
        self.alpha(i32::from(self.log[usize::from(value)]) * exponent)
    }
}

#[derive(Debug, Clone, Default)]
pub struct RsDecodeResult {
    pub data: Vec<u8>,
    pub codewords_ok: u32,
    pub codewords_failed: u32,
}

#[must_use]
pub fn deinterleave(frame: &[u8]) -> [[u8; RS_CODEWORD_LEN]; INTERLEAVE] {
    let mut codewords = [[0u8; RS_CODEWORD_LEN]; INTERLEAVE];
    for (i, &byte) in frame.iter().take(INTERLEAVED_FRAME_LEN).enumerate() {
        codewords[i % INTERLEAVE][i / INTERLEAVE] = byte;
    }
    codewords
}

#[must_use]
pub fn interleave_data(codewords: &[[u8; RS_DATA_LEN]; INTERLEAVE]) -> Vec<u8> {
    let mut out = vec![0u8; RS_DATA_LEN * INTERLEAVE];
    for pos in 0..RS_DATA_LEN {
        for cw in 0..INTERLEAVE {
            out[pos * INTERLEAVE + cw] = codewords[cw][pos];
        }
    }
    out
}

fn trim(mut p: Vec<u8>) -> Vec<u8> {
    while p.len() > 1 && p[0] == 0 {
        p.remove(0);
    }
    p
}

fn mul_poly(a: &[u8], b: &[u8]) -> Vec<u8> {
    let mut out = vec![0; a.len() + b.len() - 1];
    for (i, &x) in a.iter().enumerate() {
        for (j, &y) in b.iter().enumerate() {
            out[i + j] ^= GF.mul(x, y);
        }
    }
    trim(out)
}

fn add_poly(a: &[u8], b: &[u8]) -> Vec<u8> {
    let n = a.len().max(b.len());
    let mut out = vec![0; n];
    for i in 0..n {
        if i >= n - a.len() {
            out[i] ^= a[i - (n - a.len())];
        }
        if i >= n - b.len() {
            out[i] ^= b[i - (n - b.len())];
        }
    }
    trim(out)
}

fn scale_poly(a: &[u8], factor: u8) -> Vec<u8> {
    a.iter().map(|&x| GF.mul(x, factor)).collect()
}

fn eval_poly(p: &[u8], x: u8) -> u8 {
    p.iter().fold(0, |acc, &c| GF.mul(acc, x) ^ c)
}

fn reverse_poly(p: &[u8]) -> Vec<u8> {
    p.iter().rev().copied().collect()
}

fn generator() -> Vec<u8> {
    let mut g = vec![1];
    for i in 0..RS_PARITY_LEN {
        g = mul_poly(&g, &[1, GF.alpha((FIRST_ROOT + i as i32) * PRIMITIVE_STEP)]);
    }
    g
}

#[cfg_attr(not(test), allow(dead_code))]
#[must_use]
pub fn encode_codeword(data: &[u8; RS_DATA_LEN]) -> [u8; RS_CODEWORD_LEN] {
    let g = generator();
    let mut work = vec![0; RS_CODEWORD_LEN];
    work[..RS_DATA_LEN].copy_from_slice(data);
    for i in 0..RS_DATA_LEN {
        let factor = work[i];
        if factor != 0 {
            for j in 0..g.len() {
                work[i + j] ^= GF.mul(factor, g[j]);
            }
        }
    }
    let mut out = [0; RS_CODEWORD_LEN];
    out[..RS_DATA_LEN].copy_from_slice(data);
    out[RS_DATA_LEN..].copy_from_slice(&work[RS_DATA_LEN..]);
    out
}

#[cfg_attr(not(test), allow(dead_code))]
#[must_use]
pub fn encode_interleaved(payload: &[u8]) -> Vec<u8> {
    assert_eq!(payload.len(), RS_DATA_LEN * INTERLEAVE);
    let mut codewords = [[0u8; RS_CODEWORD_LEN]; INTERLEAVE];
    for cw in 0..INTERLEAVE {
        let mut data = [0; RS_DATA_LEN];
        for pos in 0..RS_DATA_LEN {
            data[pos] = payload[pos * INTERLEAVE + cw];
        }
        codewords[cw] = encode_codeword(&data);
    }
    let mut frame = vec![0; INTERLEAVED_FRAME_LEN];
    for (i, slot) in frame.iter_mut().enumerate() {
        *slot = codewords[i % INTERLEAVE][i / INTERLEAVE];
    }
    frame
}

fn syndromes(codeword: &[u8; RS_CODEWORD_LEN]) -> Vec<u8> {
    (0..RS_PARITY_LEN)
        .map(|i| eval_poly(codeword, GF.alpha((FIRST_ROOT + i as i32) * PRIMITIVE_STEP)))
        .collect()
}

fn find_error_locator(s: &[u8]) -> Option<Vec<u8>> {
    let mut locator = vec![1];
    let mut old = vec![1];
    for k in 0..s.len() {
        let mut discrepancy = s[k];
        for j in 1..locator.len() {
            discrepancy ^= GF.mul(locator[locator.len() - 1 - j], s[k - j]);
        }
        old.push(0);
        if discrepancy == 0 {
            continue;
        }
        if old.len() > locator.len() {
            let next = scale_poly(&old, discrepancy);
            old = scale_poly(&locator, GF.inv(discrepancy));
            locator = add_poly(&next, &scale_poly(&old, discrepancy));
        } else {
            locator = add_poly(&locator, &scale_poly(&old, discrepancy));
        }
    }
    (locator.len() - 1 <= RS_PARITY_LEN / 2).then_some(locator)
}

fn error_positions(locator: &[u8]) -> Option<Vec<usize>> {
    let expected = locator.len() - 1;
    let mut positions = Vec::with_capacity(expected);
    let locator = reverse_poly(locator);
    for i in 0..RS_CODEWORD_LEN {
        if eval_poly(&locator, GF.alpha(i as i32 * PRIMITIVE_STEP)) == 0 {
            positions.push(RS_CODEWORD_LEN - 1 - i);
        }
    }
    (positions.len() == expected).then_some(positions)
}

fn solve_error_magnitudes(s: &[u8], positions: &[usize]) -> Option<Vec<u8>> {
    let n = positions.len();
    let mut matrix = vec![vec![0u8; n + 1]; n];
    for row in 0..n {
        let evaluation_point = GF.alpha((FIRST_ROOT + row as i32) * PRIMITIVE_STEP);
        for (column, &position) in positions.iter().enumerate() {
            let degree = (RS_CODEWORD_LEN - 1 - position) as i32;
            matrix[row][column] = GF.pow(evaluation_point, degree);
        }
        matrix[row][n] = s[row];
    }

    for column in 0..n {
        let pivot = (column..n).find(|&row| matrix[row][column] != 0)?;
        matrix.swap(column, pivot);
        let inv = GF.inv(matrix[column][column]);
        for item in &mut matrix[column][column..=n] {
            *item = GF.mul(*item, inv);
        }
        for row in 0..n {
            if row == column {
                continue;
            }
            let factor = matrix[row][column];
            if factor == 0 {
                continue;
            }
            for item in column..=n {
                matrix[row][item] ^= GF.mul(factor, matrix[column][item]);
            }
        }
    }
    Some((0..n).map(|row| matrix[row][n]).collect())
}

fn correct_codeword(input: &[u8; RS_CODEWORD_LEN]) -> Option<[u8; RS_CODEWORD_LEN]> {
    let s = syndromes(input);
    if s.iter().all(|&x| x == 0) {
        return Some(*input);
    }
    let locator = find_error_locator(&s)?;
    let positions = error_positions(&locator)?;
    if positions.is_empty() || positions.len() > RS_PARITY_LEN / 2 {
        return None;
    }

    let mut corrected = *input;
    let magnitudes = solve_error_magnitudes(&s, &positions)?;
    for (&pos, &magnitude) in positions.iter().zip(&magnitudes) {
        corrected[pos] ^= magnitude;
    }
    syndromes(&corrected)
        .iter()
        .all(|&x| x == 0)
        .then_some(corrected)
}

#[must_use]
pub fn decode_interleaved(frame: &[u8]) -> RsDecodeResult {
    let codewords = deinterleave(frame);
    let mut data_out = [[0u8; RS_DATA_LEN]; INTERLEAVE];
    let mut ok = 0;
    let mut failed = 0;
    for (cw_idx, codeword) in codewords.iter().enumerate() {
        if let Some(corrected) = correct_codeword(codeword) {
            data_out[cw_idx].copy_from_slice(&corrected[..RS_DATA_LEN]);
            ok += 1;
        } else {
            failed += 1;
        }
    }
    RsDecodeResult {
        data: interleave_data(&data_out),
        codewords_ok: ok,
        codewords_failed: failed,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn sample_payload() -> Vec<u8> {
        (0..RS_DATA_LEN * INTERLEAVE)
            .map(|i| ((i * 173 + 29) % 256) as u8)
            .collect()
    }

    #[test]
    fn field_cycles_and_generator_roots() {
        assert_eq!(GF.alpha(255), 1);
        let g = generator();
        for i in 0..RS_PARITY_LEN {
            assert_eq!(
                eval_poly(&g, GF.alpha((FIRST_ROOT + i as i32) * PRIMITIVE_STEP)),
                0
            );
        }
    }

    #[test]
    fn encode_decode_round_trip_no_errors() {
        let payload = sample_payload();
        let frame = encode_interleaved(&payload);
        let result = decode_interleaved(&frame);
        assert_eq!(result.codewords_ok, 4);
        assert_eq!(result.codewords_failed, 0);
        assert_eq!(result.data, payload);
    }

    #[test]
    fn parity_matches_independent_libfec_ccsds_vector() {
        // Generated with libfec's generic encoder initialized as
        // init_rs_char(8, 0x187, 112, 11, 32, 0).
        let data: [u8; RS_DATA_LEN] =
            std::array::from_fn(|i| (i as u8).wrapping_mul(173).wrapping_add(29));
        let encoded = encode_codeword(&data);
        let expected = [
            0x72, 0xde, 0x0a, 0xcf, 0x2a, 0xa2, 0x15, 0x85, 0x03, 0x1e, 0x23, 0x8b, 0xd8, 0x7b,
            0xaf, 0x57, 0x18, 0x6d, 0x91, 0x28, 0x4a, 0x8b, 0x99, 0x79, 0xcf, 0xcc, 0x15, 0x48,
            0x0b, 0x15, 0x6d, 0xe2,
        ];
        assert_eq!(&encoded[RS_DATA_LEN..], &expected);
    }

    #[test]
    fn corrects_sixteen_errors_per_codeword() {
        let payload = sample_payload();
        let mut frame = encode_interleaved(&payload);
        for cw in 0..INTERLEAVE {
            for k in 0..RS_PARITY_LEN / 2 {
                frame[k * INTERLEAVE + cw] ^= (k as u8).wrapping_mul(37) ^ 0xA5;
            }
        }
        let result = decode_interleaved(&frame);
        assert_eq!(result.codewords_ok, 4);
        assert_eq!(result.codewords_failed, 0);
        assert_eq!(result.data, payload);
    }

    #[test]
    fn rejects_seventeen_errors() {
        let payload = sample_payload();
        let mut frame = encode_interleaved(&payload);
        for k in 0..17 {
            frame[k * INTERLEAVE] ^= (k as u8).wrapping_mul(19) ^ 0x5A;
        }
        let result = decode_interleaved(&frame);
        assert_eq!(result.codewords_failed, 1);
    }
}
