[package]
name = "dump1090"
version = "0.1.0"
edition = "2021"

[lib]
name = "dump1090"
path = "src/lib.rs"

[[bin]]
name = "dump1090"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
libc = { workspace = true }
ctrlc = "3"

[features]
default = []
rtlsdr = []
hackrf = []
soapy = []
